# Generated by Django 4.0.5 on 2022-09-17 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('team1_logo', models.ImageField(blank=True, upload_to='logo_images')),
                ('team2_logo', models.ImageField(blank=True, upload_to='logo_images')),
                ('broadcast_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('broadcast_date_and_time', models.DateTimeField()),
                ('broadcast_url', models.URLField()),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='thumbnail_images')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('live_game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cs_auth.livegame')),
            ],
        ),
    ]
